services:
  api-gateway:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=auth-blacklist
      - REDIS_PASSWORD=password123
      - REDIS_PORT=6379
      - JWT_SECRET_KEY=secret
    volumes:
      - ./gateway.conf.yaml:/gateway.conf.yaml
  auth-blacklist:
    image: redis
    ports:
      - 6379:6379
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    environment:
      - REDIS_PASSWORD=password123
